[env]
# TERM = "xterm-256color"

[window]
# decorations = "None"
decorations_theme_variant = "Dark"
dynamic_title = true

[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
size = 12

[colors.primary]
background = "#0d1117"

